json get して画面描画は完了
s-hayashi1104/tpa-03-product-service pull request #1
Opened 2018-10-09 10:44 UTC by s-hayashi1104

ただ本来であればproduct.jsを使うべきところだと思う
その後の合計金額を算出するところもproduct.js使いそうなので早めのプルリク

product.jsをrequireで呼び出して使おうとするとis not function と怒られる

2018-10-09 11:51 UTC, jonatan-alama requested changes

2018-10-09 11:51 UTC, jonatan-alama commented on server/controller.js
> +    if (products.length < num) {
`products` はidごと確認する必要がないです。

2018-10-09 11:51 UTC, jonatan-alama commented on server/controller.js
> +  const obj = { 'products': getProducts() };
基本的に、jsのobjectのkeyに`'`を使わない (jsonには使う)

2018-10-09 11:56 UTC, jonatan-alama commented on server/controller.js
> +    if (products.length < num) {
すみません、idあるかどうか確認してましたね。

idは基本的に順番で 1,2,3,4 増えてきますが、例えば２番削除すれば、今のコードではうまくいかないですね。

productsにcheckProductIdとかのメソッド追加してみてください！

2018-10-11 12:33 UTC, Mitsuru53 commented
@s-hayashi1104 さん
今回のPRに関しては、画面描写されるところまで(金額計算は含まない)という認識ですが、
合っていますでしょうか？
jonatanさんのレビュー対応に関してはokだと思います！

2018-10-11 12:34 UTC, s-hayashi1104 commented
金額計算含みです！すみません。。。

2018-10-11 12:42 UTC, Mitsuru53 commented
計算するとundefinedって出てしまいますね。。。
一度ご確認くださいまし
<img width="881" alt="2018-10-11 21 36 02" src="https://user-images.githubusercontent.com/23156390/46804803-8aae3680-cd9e-11e8-9175-f735078139ac.png">

2018-10-11 13:04 UTC, Mitsuru53 reviewed
動作は正常なことを確認できました
あとはコードのちょっとしたリファクタを行いましょう！

2018-10-11 13:04 UTC, Mitsuru53 commented on server/product.js
> +    return false;
if (!checkIds(productIds))
でいいはず

2018-10-11 13:04 UTC, Mitsuru53 commented on server/controller.js
> +  });
フラグを用意する必要は特にないかなと思います
```
    if (Number.isNaN(num)) {
      return res.status(400).json({});
    }
```

2018-10-11 13:04 UTC, Mitsuru53 commented on server/controller.js
> +  };
変数名を
selectIds ではなく productIds、
priceではなく totalとしておけば
下記のように書けてスッキリするはずです
```
  const obj = {
    productIds,
    total,
  };
```

2018-10-11 13:04 UTC, Mitsuru53 commented on server/product.js
> +    arr.push(element.id);
elementを囲む()は要らない
```
prods.forEach(element => {
```

2018-10-11 13:12 UTC, s-hayashi1104 commented on server/controller.js
> +  };
変数名とキー名一緒にするとこんな返し方できるんですね。。。
参考になります！！

2018-10-11 13:27 UTC, s-hayashi1104 commented on server/controller.js
> +  });
それforEachの中なんですよ・・・
for文に書き直しました

2018-10-12 10:00 UTC, Mitsuru53 commented
OKです！
まーじしちゃってください！

2018-10-12 10:29 UTC, merged